name: Check version coherence
on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check version coherence
      run: |
           python check-version.py