name: Testing

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Cyantities
      run: |
          # Install packages:
          sudo apt update
          sudo apt-get install -y liblapacke-dev build-essential\
                                  git openssh-client ssh cython3 \
                                  ninja-build cmake-data \
                                  cmake-extras extra-cmake-modules \
                                  wget libboost-all-dev
          python3 -m pip install --user numpy
          # Use modern GCC:
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
          # Python installs:
          python3 -m pip install --upgrade pip
          sudo apt purge python3-setuptools
          python3 -m pip install --user --verbose .
    - name: Build examples
      run: |
         cd examples/parabola/
         python3 build.py
         cd ../..
    - name: Lint with flake8
      run: |
        python3 -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 cyantities --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        # Install pytest
        python3 -m pip install pytest
        cd testing
        # Run the test suite:
        pytest -s